/**
 * SSWEB Command - Website Screenshot Tool
 * Mathithibala_Bot Pro | Professor Sahil System
 */

const axios = require('axios');

module.exports = {
  name: 'ssweb',
  aliases: ['screenshot', 'ss', 'webshot'],
  category: 'general',
  description: 'Take screenshot of any website',
  usage: '.ssweb <url>',

  async execute(sock, msg, args, extra) {
    try {
      const chatId = msg.key.remoteJid;
      const url = args.join(' ');

      if (!url) {
        return extra.reply(
          `❌ Please provide a valid website URL.\n\nExample:\n.ssweb https://google.com`
        );
      }

      // simple URL fix
      const fixedUrl = url.startsWith('http') ? url : `https://${url}`;

      await extra.reply('🌐 Capturing website screenshot...');

      // Screenshot API (stable free endpoint)
      const imageUrl = `https://image.thum.io/get/fullpage/${fixedUrl}`;

      // Send image
      await sock.sendMessage(chatId, {
        image: { url: imageUrl },
        caption:
`🌐 *Website Screenshot*

🔗 URL: ${fixedUrl}

🤖 Generated by Mathithibala_Bot Pro
👑 Professor Sahil System`
      }, { quoted: msg });

    } catch (err) {
      console.log('SSWEB Error:', err);
      extra.reply('❌ Failed to capture website screenshot.');
    }
  }
};
